class Solution:
    def intToRoman(self, num):
        rome=''
        while (num-1000)>=0:
            rome=rome+'M'
            num-=1000
        if (num-900)>=0:
            rome=rome+'CM'
            num-=900
        if (num-500)>=0:
            rome=rome+'D'
            num-=500
        if (num-400)>=0:
            rome=rome+'CD'
            num-=400
        while (num-100)>=0:
            rome=rome+'C'
            num-=100
        if (num-90)>=0:
            rome=rome+'XC'
            num-=90
        if (num-50)>=0:
            rome=rome+'L'
            num-=50
        if (num-40)>=0:
            rome=rome+'XL'
            num-=40
        while (num-10)>=0:
            rome=rome+'X'
            num-=10
        if (num-9)>=0:
            rome=rome+'IX'
            num-=9
        if (num-5)>=0:
            rome=rome+'V'
            num-=5
        if (num-4)>=0:
            rome=rome+'IV'
            num-=4
        while (num-1)>=0:
            rome=rome+'I'
            num-=1
        return rome